[2023-05-01 23:04:06,453] {processor.py:153} INFO - Started process (PID=1199) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:04:06,454] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:04:06,456] {logging_mixin.py:115} INFO - [2023-05-01 23:04:06,456] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:04:06,524] {logging_mixin.py:115} INFO - [2023-05-01 23:04:06,515] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:04:06,528] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:04:06,554] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.104 seconds
[2023-05-01 23:04:36,855] {processor.py:153} INFO - Started process (PID=1262) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:04:36,856] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:04:36,857] {logging_mixin.py:115} INFO - [2023-05-01 23:04:36,857] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:04:36,910] {logging_mixin.py:115} INFO - [2023-05-01 23:04:36,900] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:04:36,915] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:04:36,947] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.095 seconds
[2023-05-01 23:05:07,648] {processor.py:153} INFO - Started process (PID=1316) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:05:07,649] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:05:07,650] {logging_mixin.py:115} INFO - [2023-05-01 23:05:07,650] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:05:07,695] {logging_mixin.py:115} INFO - [2023-05-01 23:05:07,687] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:05:07,699] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:05:07,726] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.082 seconds
[2023-05-01 23:05:38,503] {processor.py:153} INFO - Started process (PID=1380) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:05:38,504] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:05:38,506] {logging_mixin.py:115} INFO - [2023-05-01 23:05:38,506] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:05:38,551] {logging_mixin.py:115} INFO - [2023-05-01 23:05:38,542] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:05:38,554] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:05:38,585] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.084 seconds
[2023-05-01 23:06:09,074] {processor.py:153} INFO - Started process (PID=1434) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:06:09,076] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:06:09,078] {logging_mixin.py:115} INFO - [2023-05-01 23:06:09,078] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:06:09,227] {logging_mixin.py:115} INFO - [2023-05-01 23:06:09,209] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:06:09,235] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:06:09,333] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.270 seconds
[2023-05-01 23:06:39,500] {processor.py:153} INFO - Started process (PID=1498) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:06:39,501] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:06:39,502] {logging_mixin.py:115} INFO - [2023-05-01 23:06:39,502] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:06:39,555] {logging_mixin.py:115} INFO - [2023-05-01 23:06:39,544] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:06:39,560] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:06:39,592] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.096 seconds
[2023-05-01 23:07:09,702] {processor.py:153} INFO - Started process (PID=1553) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:07:09,703] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:07:09,704] {logging_mixin.py:115} INFO - [2023-05-01 23:07:09,704] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:07:09,752] {logging_mixin.py:115} INFO - [2023-05-01 23:07:09,743] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:07:09,755] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:07:09,784] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.085 seconds
[2023-05-01 23:07:40,739] {processor.py:153} INFO - Started process (PID=1617) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:07:40,740] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:07:40,742] {logging_mixin.py:115} INFO - [2023-05-01 23:07:40,742] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:07:40,809] {logging_mixin.py:115} INFO - [2023-05-01 23:07:40,797] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:07:40,815] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:07:40,869] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.138 seconds
[2023-05-01 23:08:11,340] {processor.py:153} INFO - Started process (PID=1678) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:08:11,341] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:08:11,343] {logging_mixin.py:115} INFO - [2023-05-01 23:08:11,343] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:08:11,390] {logging_mixin.py:115} INFO - [2023-05-01 23:08:11,381] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:08:11,395] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:08:11,420] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.084 seconds
[2023-05-01 23:08:41,960] {processor.py:153} INFO - Started process (PID=1734) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:08:41,961] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:08:41,962] {logging_mixin.py:115} INFO - [2023-05-01 23:08:41,962] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:08:42,019] {logging_mixin.py:115} INFO - [2023-05-01 23:08:42,007] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:08:42,024] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:08:42,065] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.109 seconds
[2023-05-01 23:09:12,600] {processor.py:153} INFO - Started process (PID=1798) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:09:12,601] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:09:12,602] {logging_mixin.py:115} INFO - [2023-05-01 23:09:12,602] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:09:12,651] {logging_mixin.py:115} INFO - [2023-05-01 23:09:12,641] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:09:12,655] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:09:12,834] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.238 seconds
[2023-05-01 23:10:46,017] {processor.py:153} INFO - Started process (PID=57) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:10:46,025] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:10:46,028] {logging_mixin.py:115} INFO - [2023-05-01 23:10:46,027] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:10:46,137] {logging_mixin.py:115} INFO - [2023-05-01 23:10:46,116] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:10:46,143] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:10:46,278] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.285 seconds
[2023-05-01 23:11:16,495] {processor.py:153} INFO - Started process (PID=111) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:11:16,496] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:11:16,497] {logging_mixin.py:115} INFO - [2023-05-01 23:11:16,497] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:11:16,540] {logging_mixin.py:115} INFO - [2023-05-01 23:11:16,532] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:11:16,543] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:11:16,566] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.074 seconds
[2023-05-01 23:11:46,914] {processor.py:153} INFO - Started process (PID=174) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:11:46,915] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:11:46,916] {logging_mixin.py:115} INFO - [2023-05-01 23:11:46,916] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:11:46,961] {logging_mixin.py:115} INFO - [2023-05-01 23:11:46,952] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:11:46,965] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:11:46,993] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.084 seconds
[2023-05-01 23:12:17,251] {processor.py:153} INFO - Started process (PID=228) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:12:17,252] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:12:17,253] {logging_mixin.py:115} INFO - [2023-05-01 23:12:17,253] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:12:17,294] {logging_mixin.py:115} INFO - [2023-05-01 23:12:17,287] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:12:17,299] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:12:17,334] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.087 seconds
[2023-05-01 23:12:47,946] {processor.py:153} INFO - Started process (PID=292) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:12:47,948] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:12:47,950] {logging_mixin.py:115} INFO - [2023-05-01 23:12:47,950] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:12:47,994] {logging_mixin.py:115} INFO - [2023-05-01 23:12:47,986] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:12:47,999] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:12:48,032] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.089 seconds
[2023-05-01 23:13:18,416] {processor.py:153} INFO - Started process (PID=346) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:13:18,418] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:13:18,420] {logging_mixin.py:115} INFO - [2023-05-01 23:13:18,420] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:13:18,493] {logging_mixin.py:115} INFO - [2023-05-01 23:13:18,472] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:13:18,499] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:13:18,556] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.148 seconds
[2023-05-01 23:13:48,804] {processor.py:153} INFO - Started process (PID=400) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:13:48,806] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:13:48,808] {logging_mixin.py:115} INFO - [2023-05-01 23:13:48,808] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:13:48,859] {logging_mixin.py:115} INFO - [2023-05-01 23:13:48,851] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:13:48,864] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:13:48,897] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.098 seconds
[2023-05-01 23:14:19,116] {processor.py:153} INFO - Started process (PID=463) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:14:19,118] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:14:19,119] {logging_mixin.py:115} INFO - [2023-05-01 23:14:19,119] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:14:19,166] {logging_mixin.py:115} INFO - [2023-05-01 23:14:19,157] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:14:19,170] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:14:19,204] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.092 seconds
[2023-05-01 23:14:49,883] {processor.py:153} INFO - Started process (PID=517) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:14:49,885] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:14:49,886] {logging_mixin.py:115} INFO - [2023-05-01 23:14:49,886] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:14:49,937] {logging_mixin.py:115} INFO - [2023-05-01 23:14:49,929] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:14:49,940] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:14:49,973] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.094 seconds
[2023-05-01 23:15:20,436] {processor.py:153} INFO - Started process (PID=581) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:15:20,440] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:15:20,443] {logging_mixin.py:115} INFO - [2023-05-01 23:15:20,442] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:15:20,533] {logging_mixin.py:115} INFO - [2023-05-01 23:15:20,512] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:15:20,541] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:15:20,615] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.190 seconds
[2023-05-01 23:15:50,861] {processor.py:153} INFO - Started process (PID=635) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:15:50,863] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:15:50,867] {logging_mixin.py:115} INFO - [2023-05-01 23:15:50,866] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:15:50,929] {logging_mixin.py:115} INFO - [2023-05-01 23:15:50,917] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:15:50,934] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:15:50,983] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.127 seconds
[2023-05-01 23:16:21,839] {processor.py:153} INFO - Started process (PID=689) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:16:21,841] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:16:21,843] {logging_mixin.py:115} INFO - [2023-05-01 23:16:21,843] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:16:21,900] {logging_mixin.py:115} INFO - [2023-05-01 23:16:21,889] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:16:21,904] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:16:21,949] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.117 seconds
[2023-05-01 23:16:52,905] {processor.py:153} INFO - Started process (PID=743) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:16:52,909] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:16:52,911] {logging_mixin.py:115} INFO - [2023-05-01 23:16:52,911] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:16:52,976] {logging_mixin.py:115} INFO - [2023-05-01 23:16:52,964] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:16:52,982] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:16:53,048] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.149 seconds
[2023-05-01 23:17:23,192] {processor.py:153} INFO - Started process (PID=797) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:17:23,195] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:17:23,197] {logging_mixin.py:115} INFO - [2023-05-01 23:17:23,196] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:17:23,271] {logging_mixin.py:115} INFO - [2023-05-01 23:17:23,256] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:17:23,276] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:17:23,330] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.146 seconds
[2023-05-01 23:17:53,523] {processor.py:153} INFO - Started process (PID=851) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:17:53,524] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:17:53,526] {logging_mixin.py:115} INFO - [2023-05-01 23:17:53,526] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:17:53,580] {logging_mixin.py:115} INFO - [2023-05-01 23:17:53,570] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:17:53,586] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:17:53,624] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.106 seconds
[2023-05-01 23:18:23,990] {processor.py:153} INFO - Started process (PID=914) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:18:23,991] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:18:23,993] {logging_mixin.py:115} INFO - [2023-05-01 23:18:23,992] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:18:24,040] {logging_mixin.py:115} INFO - [2023-05-01 23:18:24,031] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:18:24,043] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:18:24,075] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.088 seconds
[2023-05-01 23:18:55,039] {processor.py:153} INFO - Started process (PID=968) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:18:55,040] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:18:55,041] {logging_mixin.py:115} INFO - [2023-05-01 23:18:55,041] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:18:55,093] {logging_mixin.py:115} INFO - [2023-05-01 23:18:55,082] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:18:55,097] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:18:55,131] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.095 seconds
[2023-05-01 23:19:25,965] {processor.py:153} INFO - Started process (PID=1031) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:19:25,966] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:19:25,968] {logging_mixin.py:115} INFO - [2023-05-01 23:19:25,968] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:19:26,021] {logging_mixin.py:115} INFO - [2023-05-01 23:19:26,011] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:19:26,025] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:19:26,053] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.091 seconds
[2023-05-01 23:19:56,589] {processor.py:153} INFO - Started process (PID=1085) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:19:56,590] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:19:56,592] {logging_mixin.py:115} INFO - [2023-05-01 23:19:56,591] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:19:56,634] {logging_mixin.py:115} INFO - [2023-05-01 23:19:56,626] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:19:56,639] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:19:56,677] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.091 seconds
[2023-05-01 23:20:27,112] {processor.py:153} INFO - Started process (PID=1148) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:20:27,114] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:20:27,115] {logging_mixin.py:115} INFO - [2023-05-01 23:20:27,115] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:20:27,163] {logging_mixin.py:115} INFO - [2023-05-01 23:20:27,152] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:20:27,167] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:20:27,196] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.088 seconds
[2023-05-01 23:20:57,465] {processor.py:153} INFO - Started process (PID=1202) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:20:57,473] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:20:57,475] {logging_mixin.py:115} INFO - [2023-05-01 23:20:57,474] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:20:57,601] {logging_mixin.py:115} INFO - [2023-05-01 23:20:57,573] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:20:57,605] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:20:57,688] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.228 seconds
[2023-05-01 23:25:57,718] {processor.py:153} INFO - Started process (PID=1216) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:25:57,720] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:25:57,721] {logging_mixin.py:115} INFO - [2023-05-01 23:25:57,721] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:25:57,766] {logging_mixin.py:115} INFO - [2023-05-01 23:25:57,758] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:25:57,770] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:25:57,938] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.223 seconds
[2023-05-01 23:26:28,117] {processor.py:153} INFO - Started process (PID=1270) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:26:28,118] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:26:28,120] {logging_mixin.py:115} INFO - [2023-05-01 23:26:28,119] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:26:28,161] {logging_mixin.py:115} INFO - [2023-05-01 23:26:28,152] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:26:28,164] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:26:28,387] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.276 seconds
[2023-05-01 23:26:58,946] {processor.py:153} INFO - Started process (PID=1325) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:26:58,948] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:26:58,949] {logging_mixin.py:115} INFO - [2023-05-01 23:26:58,949] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:26:58,996] {logging_mixin.py:115} INFO - [2023-05-01 23:26:58,987] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:26:58,999] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:26:59,246] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.303 seconds
[2023-05-01 23:27:29,353] {processor.py:153} INFO - Started process (PID=1390) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:27:29,354] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:27:29,355] {logging_mixin.py:115} INFO - [2023-05-01 23:27:29,355] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:27:29,403] {logging_mixin.py:115} INFO - [2023-05-01 23:27:29,394] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:27:29,407] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:27:29,575] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.225 seconds
[2023-05-01 23:27:59,747] {processor.py:153} INFO - Started process (PID=1445) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:27:59,748] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:27:59,749] {logging_mixin.py:115} INFO - [2023-05-01 23:27:59,749] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:27:59,796] {logging_mixin.py:115} INFO - [2023-05-01 23:27:59,787] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:27:59,801] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:27:59,988] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.244 seconds
[2023-05-01 23:28:30,688] {processor.py:153} INFO - Started process (PID=1500) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:28:30,691] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:28:30,694] {logging_mixin.py:115} INFO - [2023-05-01 23:28:30,694] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:28:30,791] {logging_mixin.py:115} INFO - [2023-05-01 23:28:30,766] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:28:30,801] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:28:31,237] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.555 seconds
[2023-05-01 23:35:54,940] {processor.py:153} INFO - Started process (PID=55) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:35:54,943] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:35:54,946] {logging_mixin.py:115} INFO - [2023-05-01 23:35:54,946] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:35:55,066] {logging_mixin.py:115} INFO - [2023-05-01 23:35:55,038] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:35:55,074] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:35:55,162] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.246 seconds
[2023-05-01 23:36:25,574] {processor.py:153} INFO - Started process (PID=99) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:36:25,575] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:36:25,577] {logging_mixin.py:115} INFO - [2023-05-01 23:36:25,576] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:36:25,633] {logging_mixin.py:115} INFO - [2023-05-01 23:36:25,623] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:36:25,638] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:36:25,670] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.100 seconds
[2023-05-01 23:36:55,990] {processor.py:153} INFO - Started process (PID=162) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:36:55,993] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:36:55,995] {logging_mixin.py:115} INFO - [2023-05-01 23:36:55,995] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:36:56,065] {logging_mixin.py:115} INFO - [2023-05-01 23:36:56,051] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:36:56,071] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:36:56,118] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.152 seconds
[2023-05-01 23:37:26,877] {processor.py:153} INFO - Started process (PID=216) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:37:26,879] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:37:26,881] {logging_mixin.py:115} INFO - [2023-05-01 23:37:26,880] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:37:26,945] {logging_mixin.py:115} INFO - [2023-05-01 23:37:26,934] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:37:26,950] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:37:26,983] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.112 seconds
[2023-05-01 23:37:57,562] {processor.py:153} INFO - Started process (PID=270) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:37:57,565] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:37:57,569] {logging_mixin.py:115} INFO - [2023-05-01 23:37:57,568] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:37:57,642] {logging_mixin.py:115} INFO - [2023-05-01 23:37:57,627] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:37:57,649] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:37:57,692] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.136 seconds
[2023-05-01 23:38:27,971] {processor.py:153} INFO - Started process (PID=325) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:38:27,977] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:38:27,981] {logging_mixin.py:115} INFO - [2023-05-01 23:38:27,980] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:38:28,114] {logging_mixin.py:115} INFO - [2023-05-01 23:38:28,087] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:38:28,122] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:38:28,201] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.239 seconds
[2023-05-01 23:38:58,640] {processor.py:153} INFO - Started process (PID=380) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:38:58,642] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:38:58,644] {logging_mixin.py:115} INFO - [2023-05-01 23:38:58,644] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:38:58,704] {logging_mixin.py:115} INFO - [2023-05-01 23:38:58,692] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:38:58,708] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:38:58,750] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.116 seconds
[2023-05-01 23:39:29,205] {processor.py:153} INFO - Started process (PID=435) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:39:29,207] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:39:29,211] {logging_mixin.py:115} INFO - [2023-05-01 23:39:29,211] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:39:29,321] {logging_mixin.py:115} INFO - [2023-05-01 23:39:29,299] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:39:29,331] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:39:29,397] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.207 seconds
[2023-05-01 23:40:01,445] {processor.py:153} INFO - Started process (PID=492) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:40:01,450] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:40:01,454] {logging_mixin.py:115} INFO - [2023-05-01 23:40:01,454] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:40:01,595] {logging_mixin.py:115} INFO - [2023-05-01 23:40:01,564] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:40:01,646] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:40:01,769] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.342 seconds
[2023-05-01 23:40:32,729] {processor.py:153} INFO - Started process (PID=543) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:40:32,731] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:40:32,734] {logging_mixin.py:115} INFO - [2023-05-01 23:40:32,734] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:40:32,820] {logging_mixin.py:115} INFO - [2023-05-01 23:40:32,800] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:40:32,827] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:40:32,874] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.149 seconds
[2023-05-01 23:41:02,963] {processor.py:153} INFO - Started process (PID=597) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:41:02,964] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:41:02,966] {logging_mixin.py:115} INFO - [2023-05-01 23:41:02,965] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:41:03,072] {logging_mixin.py:115} INFO - [2023-05-01 23:41:03,058] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:41:03,080] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:41:03,123] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.164 seconds
[2023-05-01 23:41:33,357] {processor.py:153} INFO - Started process (PID=651) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:41:33,358] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:41:33,359] {logging_mixin.py:115} INFO - [2023-05-01 23:41:33,359] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:41:33,407] {logging_mixin.py:115} INFO - [2023-05-01 23:41:33,397] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:41:33,411] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:41:33,432] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.077 seconds
[2023-05-01 23:42:03,836] {processor.py:153} INFO - Started process (PID=705) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:42:03,838] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:42:03,841] {logging_mixin.py:115} INFO - [2023-05-01 23:42:03,841] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:42:03,948] {logging_mixin.py:115} INFO - [2023-05-01 23:42:03,923] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:42:03,956] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:42:04,029] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.210 seconds
[2023-05-01 23:42:34,179] {processor.py:153} INFO - Started process (PID=759) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:42:34,180] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:42:34,182] {logging_mixin.py:115} INFO - [2023-05-01 23:42:34,182] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:42:34,254] {logging_mixin.py:115} INFO - [2023-05-01 23:42:34,241] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:42:34,260] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:42:34,298] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.125 seconds
[2023-05-01 23:43:08,766] {processor.py:153} INFO - Started process (PID=813) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:43:08,937] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:43:09,076] {logging_mixin.py:115} INFO - [2023-05-01 23:43:09,076] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:43:12,111] {logging_mixin.py:115} INFO - [2023-05-01 23:43:11,478] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:43:12,282] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:43:12,377] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 3.619 seconds
[2023-05-01 23:43:42,714] {processor.py:153} INFO - Started process (PID=868) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:43:42,716] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:43:42,718] {logging_mixin.py:115} INFO - [2023-05-01 23:43:42,718] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:43:42,819] {logging_mixin.py:115} INFO - [2023-05-01 23:43:42,777] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:43:42,875] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:43:42,977] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.269 seconds
[2023-05-01 23:44:13,683] {processor.py:153} INFO - Started process (PID=922) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:44:13,685] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:44:13,687] {logging_mixin.py:115} INFO - [2023-05-01 23:44:13,686] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:44:13,766] {logging_mixin.py:115} INFO - [2023-05-01 23:44:13,751] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:44:13,772] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:44:13,819] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.143 seconds
[2023-05-01 23:44:44,139] {processor.py:153} INFO - Started process (PID=976) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:44:44,141] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:44:44,143] {logging_mixin.py:115} INFO - [2023-05-01 23:44:44,142] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:44:44,215] {logging_mixin.py:115} INFO - [2023-05-01 23:44:44,201] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:44:44,221] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:44:44,255] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.122 seconds
[2023-05-01 23:45:14,680] {processor.py:153} INFO - Started process (PID=1030) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:45:14,681] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:45:14,684] {logging_mixin.py:115} INFO - [2023-05-01 23:45:14,683] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:45:14,750] {logging_mixin.py:115} INFO - [2023-05-01 23:45:14,738] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:45:14,756] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:45:14,798] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.124 seconds
[2023-05-01 23:45:44,944] {processor.py:153} INFO - Started process (PID=1093) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:45:44,945] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:45:44,947] {logging_mixin.py:115} INFO - [2023-05-01 23:45:44,947] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:45:45,013] {logging_mixin.py:115} INFO - [2023-05-01 23:45:45,000] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:45:45,020] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:45:45,072] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.133 seconds
[2023-05-01 23:46:16,032] {processor.py:153} INFO - Started process (PID=1147) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:46:16,053] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:46:16,061] {logging_mixin.py:115} INFO - [2023-05-01 23:46:16,060] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:46:16,325] {logging_mixin.py:115} INFO - [2023-05-01 23:46:16,298] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:46:16,343] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:46:16,432] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.407 seconds
[2023-05-01 23:46:46,583] {processor.py:153} INFO - Started process (PID=1202) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:46:46,584] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:46:46,586] {logging_mixin.py:115} INFO - [2023-05-01 23:46:46,585] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:46:46,645] {logging_mixin.py:115} INFO - [2023-05-01 23:46:46,633] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:46:46,650] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:46:46,677] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.097 seconds
[2023-05-01 23:47:16,869] {processor.py:153} INFO - Started process (PID=1265) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:47:16,870] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:47:16,871] {logging_mixin.py:115} INFO - [2023-05-01 23:47:16,871] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:47:16,922] {logging_mixin.py:115} INFO - [2023-05-01 23:47:16,912] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:47:16,927] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:47:16,955] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.090 seconds
[2023-05-01 23:47:47,443] {processor.py:153} INFO - Started process (PID=1318) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:47:47,444] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:47:47,445] {logging_mixin.py:115} INFO - [2023-05-01 23:47:47,445] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:47:47,494] {logging_mixin.py:115} INFO - [2023-05-01 23:47:47,484] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:47:47,499] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:47:47,531] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.093 seconds
[2023-05-01 23:48:17,890] {processor.py:153} INFO - Started process (PID=1382) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:48:17,892] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:48:17,895] {logging_mixin.py:115} INFO - [2023-05-01 23:48:17,895] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:48:17,953] {logging_mixin.py:115} INFO - [2023-05-01 23:48:17,942] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:48:17,957] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:48:17,989] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.106 seconds
[2023-05-01 23:48:48,988] {processor.py:153} INFO - Started process (PID=1436) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:48:48,989] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:48:48,991] {logging_mixin.py:115} INFO - [2023-05-01 23:48:48,991] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:48:49,050] {logging_mixin.py:115} INFO - [2023-05-01 23:48:49,037] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:48:49,054] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:48:49,091] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.107 seconds
[2023-05-01 23:49:19,276] {processor.py:153} INFO - Started process (PID=1490) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:49:19,277] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:49:19,279] {logging_mixin.py:115} INFO - [2023-05-01 23:49:19,278] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:49:19,319] {logging_mixin.py:115} INFO - [2023-05-01 23:49:19,312] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:49:19,324] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:49:19,346] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.073 seconds
[2023-05-01 23:49:49,947] {processor.py:153} INFO - Started process (PID=1555) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:49:49,949] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:49:49,951] {logging_mixin.py:115} INFO - [2023-05-01 23:49:49,951] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:49:50,016] {logging_mixin.py:115} INFO - [2023-05-01 23:49:50,005] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:49:50,021] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:49:50,073] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.131 seconds
[2023-05-01 23:50:20,224] {processor.py:153} INFO - Started process (PID=1609) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:50:20,226] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:50:20,228] {logging_mixin.py:115} INFO - [2023-05-01 23:50:20,228] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:50:20,316] {logging_mixin.py:115} INFO - [2023-05-01 23:50:20,292] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:50:20,325] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:50:20,389] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.171 seconds
[2023-05-01 23:50:50,472] {processor.py:153} INFO - Started process (PID=1663) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:50:50,473] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:50:50,474] {logging_mixin.py:115} INFO - [2023-05-01 23:50:50,474] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:50:50,519] {logging_mixin.py:115} INFO - [2023-05-01 23:50:50,511] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:50:50,522] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:50:50,559] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.090 seconds
[2023-05-01 23:51:21,221] {processor.py:153} INFO - Started process (PID=1726) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:51:21,223] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:51:21,225] {logging_mixin.py:115} INFO - [2023-05-01 23:51:21,225] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:51:21,276] {logging_mixin.py:115} INFO - [2023-05-01 23:51:21,266] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:51:21,280] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:51:21,310] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.096 seconds
[2023-05-01 23:51:51,369] {processor.py:153} INFO - Started process (PID=1789) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:51:51,370] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:51:51,371] {logging_mixin.py:115} INFO - [2023-05-01 23:51:51,371] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:51:51,422] {logging_mixin.py:115} INFO - [2023-05-01 23:51:51,412] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:51:51,425] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:51:51,467] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.102 seconds
[2023-05-01 23:52:22,248] {processor.py:153} INFO - Started process (PID=1843) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:52:22,249] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:52:22,251] {logging_mixin.py:115} INFO - [2023-05-01 23:52:22,251] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:52:22,293] {logging_mixin.py:115} INFO - [2023-05-01 23:52:22,284] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:52:22,296] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:52:22,322] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.078 seconds
[2023-05-01 23:52:52,820] {processor.py:153} INFO - Started process (PID=1907) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:52:52,821] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:52:52,822] {logging_mixin.py:115} INFO - [2023-05-01 23:52:52,822] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:52:52,868] {logging_mixin.py:115} INFO - [2023-05-01 23:52:52,859] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:52:52,872] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:52:52,905] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.089 seconds
[2023-05-01 23:53:23,785] {processor.py:153} INFO - Started process (PID=1961) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:53:23,786] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:53:23,787] {logging_mixin.py:115} INFO - [2023-05-01 23:53:23,787] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:53:23,824] {logging_mixin.py:115} INFO - [2023-05-01 23:53:23,817] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:53:23,828] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:53:23,851] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.068 seconds
[2023-05-01 23:53:54,063] {processor.py:153} INFO - Started process (PID=2024) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:53:54,064] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:53:54,065] {logging_mixin.py:115} INFO - [2023-05-01 23:53:54,065] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:53:54,105] {logging_mixin.py:115} INFO - [2023-05-01 23:53:54,098] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:53:54,109] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:53:54,131] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.071 seconds
[2023-05-01 23:54:24,312] {processor.py:153} INFO - Started process (PID=2078) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:54:24,313] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:54:24,314] {logging_mixin.py:115} INFO - [2023-05-01 23:54:24,313] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:54:24,351] {logging_mixin.py:115} INFO - [2023-05-01 23:54:24,343] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:54:24,354] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:54:24,378] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.070 seconds
[2023-05-01 23:54:54,668] {processor.py:153} INFO - Started process (PID=2141) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:54:54,669] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:54:54,670] {logging_mixin.py:115} INFO - [2023-05-01 23:54:54,670] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:54:54,719] {logging_mixin.py:115} INFO - [2023-05-01 23:54:54,710] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:54:54,723] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:54:54,756] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.091 seconds
[2023-05-01 23:55:25,009] {processor.py:153} INFO - Started process (PID=2196) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:55:25,011] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:55:25,012] {logging_mixin.py:115} INFO - [2023-05-01 23:55:25,012] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:55:25,066] {logging_mixin.py:115} INFO - [2023-05-01 23:55:25,055] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:55:25,070] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:55:25,102] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.096 seconds
[2023-05-01 23:55:55,606] {processor.py:153} INFO - Started process (PID=2259) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:55:55,607] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:55:55,608] {logging_mixin.py:115} INFO - [2023-05-01 23:55:55,608] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:55:55,667] {logging_mixin.py:115} INFO - [2023-05-01 23:55:55,656] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:55:55,670] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:55:55,695] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.093 seconds
[2023-05-01 23:56:26,607] {processor.py:153} INFO - Started process (PID=2316) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:56:26,609] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:56:26,610] {logging_mixin.py:115} INFO - [2023-05-01 23:56:26,610] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:56:26,675] {logging_mixin.py:115} INFO - [2023-05-01 23:56:26,663] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:56:26,680] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:56:26,710] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.110 seconds
[2023-05-01 23:56:56,791] {processor.py:153} INFO - Started process (PID=2377) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:56:56,792] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:56:56,793] {logging_mixin.py:115} INFO - [2023-05-01 23:56:56,793] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:56:56,838] {logging_mixin.py:115} INFO - [2023-05-01 23:56:56,829] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:56:56,841] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:56:56,863] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.075 seconds
[2023-05-01 23:57:27,062] {processor.py:153} INFO - Started process (PID=2440) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:57:27,063] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:57:27,064] {logging_mixin.py:115} INFO - [2023-05-01 23:57:27,064] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:57:27,119] {logging_mixin.py:115} INFO - [2023-05-01 23:57:27,108] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:57:27,123] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:57:27,150] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.091 seconds
[2023-05-01 23:57:57,222] {processor.py:153} INFO - Started process (PID=2494) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:57:57,224] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:57:57,225] {logging_mixin.py:115} INFO - [2023-05-01 23:57:57,225] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:57:57,271] {logging_mixin.py:115} INFO - [2023-05-01 23:57:57,263] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:57:57,275] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:57:57,295] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.076 seconds
[2023-05-01 23:58:27,613] {processor.py:153} INFO - Started process (PID=2557) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:58:27,615] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:58:27,616] {logging_mixin.py:115} INFO - [2023-05-01 23:58:27,616] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:58:27,673] {logging_mixin.py:115} INFO - [2023-05-01 23:58:27,662] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:58:27,677] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:58:27,710] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.102 seconds
[2023-05-01 23:58:57,941] {processor.py:153} INFO - Started process (PID=2620) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:58:57,943] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:58:57,944] {logging_mixin.py:115} INFO - [2023-05-01 23:58:57,944] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:58:57,999] {logging_mixin.py:115} INFO - [2023-05-01 23:58:57,988] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:58:58,003] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:58:58,052] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.115 seconds
[2023-05-01 23:59:28,529] {processor.py:153} INFO - Started process (PID=2674) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:59:28,531] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:59:28,533] {logging_mixin.py:115} INFO - [2023-05-01 23:59:28,532] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:59:28,588] {logging_mixin.py:115} INFO - [2023-05-01 23:59:28,579] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:59:28,592] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:59:28,612] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.087 seconds
[2023-05-01 23:59:58,895] {processor.py:153} INFO - Started process (PID=2737) to work on /opt/airflow/dags/files/_etl.py
[2023-05-01 23:59:58,896] {processor.py:641} INFO - Processing file /opt/airflow/dags/files/_etl.py for tasks to queue
[2023-05-01 23:59:58,897] {logging_mixin.py:115} INFO - [2023-05-01 23:59:58,897] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:59:58,943] {logging_mixin.py:115} INFO - [2023-05-01 23:59:58,933] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/files/_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/files/_etl.py", line 2, in <module>
    import yfinance as yf
ModuleNotFoundError: No module named 'yfinance'
[2023-05-01 23:59:58,947] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/files/_etl.py
[2023-05-01 23:59:58,971] {processor.py:161} INFO - Processing /opt/airflow/dags/files/_etl.py took 0.079 seconds
