[2023-05-07 19:28:13,167] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: riskthinking_ai_de.download_data manual__2023-05-07T19:28:06.277292+00:00 [queued]>
[2023-05-07 19:28:13,184] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: riskthinking_ai_de.download_data manual__2023-05-07T19:28:06.277292+00:00 [queued]>
[2023-05-07 19:28:13,185] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-07 19:28:13,187] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-05-07 19:28:13,187] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-07 19:28:13,212] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): download_data> on 2023-05-07 19:28:06.277292+00:00
[2023-05-07 19:28:13,221] {standard_task_runner.py:52} INFO - Started process 7567 to run task
[2023-05-07 19:28:13,226] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'riskthinking_ai_de', 'download_data', 'manual__2023-05-07T19:28:06.277292+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/files/rt_ai_etl.py', '--cfg-path', '/tmp/tmp6wdhg0dc', '--error-file', '/tmp/tmpjo6xw9ha']
[2023-05-07 19:28:13,229] {standard_task_runner.py:80} INFO - Job 257: Subtask download_data
[2023-05-07 19:28:13,321] {task_command.py:369} INFO - Running <TaskInstance: riskthinking_ai_de.download_data manual__2023-05-07T19:28:06.277292+00:00 [running]> on host 16ca7fe0df6c
[2023-05-07 19:28:13,450] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=riskthinking_ai_de
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T19:28:06.277292+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-07T19:28:06.277292+00:00
[2023-05-07 19:28:13,452] {logging_mixin.py:115} INFO - Downloading data for A
[2023-05-07 19:28:13,455] {logging_mixin.py:115} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'
[2023-05-07 19:28:13,456] {logging_mixin.py:115} INFO - TzCache will not be used.
[2023-05-07 19:28:13,457] {logging_mixin.py:115} INFO - Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2023-05-07 19:28:13,945] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:28:13,949] {logging_mixin.py:115} INFO - Downloading data for AA
[2023-05-07 19:28:14,637] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:28:14,640] {logging_mixin.py:115} INFO - Downloading data for AAAU
[2023-05-07 19:28:15,083] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:28:15,089] {logging_mixin.py:115} INFO - Downloading data for AADR
[2023-05-07 19:28:15,564] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:28:15,594] {logging_mixin.py:115} INFO - processed 328 rows
[2023-05-07 19:28:15,595] {python.py:173} INFO - Done. Returned value was: yfinance_data.parquet
[2023-05-07 19:28:15,644] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=riskthinking_ai_de, task_id=download_data, execution_date=20230507T192806, start_date=20230507T192813, end_date=20230507T192815
[2023-05-07 19:28:15,691] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-07 19:28:15,765] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
