[2023-05-07 19:43:53,761] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: riskthinking_ai_de.download_data manual__2023-05-07T19:43:47.683022+00:00 [queued]>
[2023-05-07 19:43:53,779] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: riskthinking_ai_de.download_data manual__2023-05-07T19:43:47.683022+00:00 [queued]>
[2023-05-07 19:43:53,780] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-05-07 19:43:53,782] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-05-07 19:43:53,783] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-05-07 19:43:53,807] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): download_data> on 2023-05-07 19:43:47.683022+00:00
[2023-05-07 19:43:53,814] {standard_task_runner.py:52} INFO - Started process 8274 to run task
[2023-05-07 19:43:53,818] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'riskthinking_ai_de', 'download_data', 'manual__2023-05-07T19:43:47.683022+00:00', '--job-id', '263', '--raw', '--subdir', 'DAGS_FOLDER/files/rt_ai_etl.py', '--cfg-path', '/tmp/tmp2q8e96_y', '--error-file', '/tmp/tmpzst1vpp9']
[2023-05-07 19:43:53,820] {standard_task_runner.py:80} INFO - Job 263: Subtask download_data
[2023-05-07 19:43:53,942] {task_command.py:369} INFO - Running <TaskInstance: riskthinking_ai_de.download_data manual__2023-05-07T19:43:47.683022+00:00 [running]> on host 16ca7fe0df6c
[2023-05-07 19:43:54,103] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=riskthinking_ai_de
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T19:43:47.683022+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-07T19:43:47.683022+00:00
[2023-05-07 19:43:54,106] {logging_mixin.py:115} INFO - Downloading data for A
[2023-05-07 19:43:54,111] {logging_mixin.py:115} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 13] Permission denied: '/home/***/.cache/py-yfinance'
[2023-05-07 19:43:54,112] {logging_mixin.py:115} INFO - TzCache will not be used.
[2023-05-07 19:43:54,113] {logging_mixin.py:115} INFO - Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2023-05-07 19:43:54,650] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:43:54,654] {logging_mixin.py:115} INFO - Downloading data for AA
[2023-05-07 19:43:55,442] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:43:55,447] {logging_mixin.py:115} INFO - Downloading data for AAAU
[2023-05-07 19:43:55,862] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:43:55,868] {logging_mixin.py:115} INFO - Downloading data for AADR
[2023-05-07 19:43:56,290] {logging_mixin.py:115} INFO - [*********************100%***********************]  1 of 1 completed
[2023-05-07 19:43:56,399] {logging_mixin.py:115} INFO - processed 328 rows
[2023-05-07 19:43:56,401] {python.py:173} INFO - Done. Returned value was: yfinance_data.parquet
[2023-05-07 19:43:56,436] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=riskthinking_ai_de, task_id=download_data, execution_date=20230507T194347, start_date=20230507T194353, end_date=20230507T194356
[2023-05-07 19:43:56,484] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-05-07 19:43:56,549] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
